version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 4000:4000
    env_file:
      - backend/.env
  users-service:
    build:
      context: .
      dockerfile: microservices/users-service/Dockerfile
    ports:
      - 50051:50051
    env_file:
      - microservices/users-service/.env

  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database/.env
