name: Rust

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: All Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: just fmt
      - name: Lint
        run: just lint
      - name: Test
        run: just test
